# Generated by Django 3.1.4 on 2021-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
