# Generated by Django 3.1.4 on 2021-01-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='aa', max_length=300),
            preserve_default=False,
        ),
    ]
